server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html login.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /api/auth/ { proxy_pass http://auth-service:5001/; }
    location /api/catalog/ { proxy_pass http://catalog-service:5003/; }
    location /api/cart/ { proxy_pass http://cart-service:5002/; }
    location /api/booking/ { proxy_pass http://booking-service:5004/; }
    location /api/payment/ { proxy_pass http://payment-service:5005/; }
    location /api/notification/ { proxy_pass http://notification-service:5006/; }
}
